# SPDX-License-Identifier: GPL-2.0
ARG BASE
FROM $BASE

RUN apt -y update -qq && apt -y upgrade && \
	DEBIAN_FRONTEND=noninteractive apt -y install \
	--no-install-recommends --no-install-suggests \
		dirmngr \
		less \
		strace \
		libmemory-usage-perl \
		libbio-db-hts-perl \
	&& \
	apt -y clean && rm -rf /var/lib/apt/lists/* /tmp/*

WORKDIR /app
ENTRYPOINT [ "perl" ]
